version: '3.8'

services:
  nextjs:
    image: ${NEXT_IMAGE}
    working_dir: /app
    ports:
      - "${NEXT_PORT}:3000"
    volumes:
      - /data/nextjs:/app
    command: npm run start
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
