version: '3.8'  # Docker Compose 파일 형식 버전

services:
  # Harbor 로그 서비스: 모든 컨테이너의 로그를 중앙 집중화하여 관리
  log:
    image: goharbor/harbor-log:v2.12.2  # Harbor 로그 수집 컨테이너 이미지
    container_name: harbor-log          # 컨테이너 이름 지정
    restart: always                     # 컨테이너 자동 재시작 설정
    cap_drop:
      - ALL                            # 모든 Linux 기능 제거 (보안 강화)
    cap_add:                           # 필요한 Linux 기능만 추가
      - CHOWN                          # 파일 소유권 변경 권한
      - DAC_OVERRIDE                   # 파일 접근 권한 재정의
      - SETGID                         # 그룹 ID 설정 권한
      - SETUID                         # 사용자 ID 설정 권한
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - type: bind
        source: ./common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
      - type: bind
        source: ./common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor

  # Docker 레지스트리: 컨테이너 이미지 저장 및 배포
  registry:
    image: goharbor/registry-photon:v2.12.2  # Harbor 레지스트리 이미지
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z            # 이미지 저장소 경로
      - ./common/config/registry/:/etc/registry/:z  # 레지스트리 설정
      # SSL 인증서 관련 설정
      - type: bind
        source: /data/secret/registry/root.crt    # 루트 인증서
        target: /etc/registry/root.crt
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registry"

  # 레지스트리 컨트롤러: 레지스트리 관리 인터페이스
  registryctl:
    image: goharbor/harbor-registryctl:v2.12.2
    container_name: registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registryctl"

  # PostgreSQL: Harbor 메타데이터 저장용 데이터베이스
  postgresql:
    image: goharbor/harbor-db:v2.12.2      # Harbor 전용 PostgreSQL 이미지
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "postgresql"
    shm_size: '1gb'                         # 공유 메모리 크기 설정

  # Harbor 코어: REST API 및 주요 비즈니스 로직 처리
  core:
    image: goharbor/harbor-core:v2.12.2
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /data/ca_download/:/etc/core/ca/:z  # 인증서 다운로드 경로
      - /data/:/data/:z                     # Harbor 데이터 저장소
      - ./common/config/core/certificates/:/etc/core/certificates/:z  # 인증서 설정
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /data/secret/keys/secretkey
        target: /etc/core/key
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "core"

  # 웹 UI: 사용자 인터페이스 제공
  portal:
    image: goharbor/harbor-portal:v2.12.2
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE                    # 네트워크 포트 바인딩 권한
    volumes:
      - type: bind
        source: ./common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "portal"

  # 작업 처리: 비동기 작업 실행 (복제/스캔)
  jobservice:
    image: goharbor/harbor-jobservice:v2.12.2
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/job_logs:/var/log/jobs:z     # 작업 로그 저장
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "jobservice"

  # Redis: 캐시 및 세션 관리
  redis:
    image: goharbor/redis-photon:v2.12.2
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/redis:/var/lib/redis         # Redis 데이터 저장소
    networks:
      harbor:
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "redis"

  # Nginx: 리버스 프록시 및 SSL 종단점
  proxy:
    image: goharbor/nginx-photon:v2.12.2
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./common/config/nginx:/etc/nginx:z
      - /data/secret/cert:/etc/cert:z
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    ports:
      - 80:8080                            # HTTP 포트
      - 443:8443                           # HTTPS 포트
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "proxy"

# 네트워크 설정
networks:
  harbor:
    external: false                         # Harbor 전용 격리된 네트워크 생성
