version: '3.8'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - /data/certs/combined:/etc/nginx/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
