version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-security
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "9000:9000"
    networks:
      - security-network
    depends_on:
      - sonarqube
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_WEB_PORT=9000
      - SONAR_WEB_CONTEXT=/
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - sonar.web.host=172.16.10.30
    volumes:
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - security-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  sonarqube-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - /data/sonarqube/postgresql:/var/lib/postgresql/data
    networks:
      - security-network
    restart: unless-stopped

  zap:
    image: owasp/zap2docker-stable
    container_name: owasp-zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8080:8080"
    volumes:
      - /data/zap/data:/zap/data
    networks:
      - security-network
    restart: unless-stopped

networks:
  security-network:
    driver: bridge
