version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    environment:
      - STATS_PORT=${HAPROXY_STATS_PORT:-8404}
      - STATS_USER=${HAPROXY_STATS_USER:-admin}
      - STATS_PASSWORD=${HAPROXY_STATS_PASSWORD:-admin}
    # 볼륨 설정
    volumes:
      # 설정 파일
      - ../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # SSL 인증서
      - /data/certs/combined:/etc/ssl/certs:ro
      # 로그 및 데이터
      - /data/haproxy/logs:/var/log/haproxy:rw
      - /data/haproxy/lib:/var/lib/haproxy:rw
      - /data/haproxy/data:/usr/local/etc/haproxy/data:rw
      # 소켓 파일용 볼륨
      - /var/run/haproxy:/var/run/haproxy:rw
    # tmpfs 제거하고 권한 설정 변경
    restart: unless-stopped
    networks:
      - proxy-net
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8404 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  proxy-net:
    driver: bridge
