version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    user: "99:99"  # HAProxy 실제 컨테이너 UID:GID
    # 시스템 제한 설정
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 2048
        hard: 4096
    # 리소스 제한 설정
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
          pids: 100    # pids_limit를 여기로 통합
        reservations:
          cpus: '0.5'
          memory: 512M
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    environment:
      - STATS_PORT=${HAPROXY_STATS_PORT:-8404}
      - STATS_USER=${HAPROXY_STATS_USER:-admin}
      - STATS_PASSWORD=${HAPROXY_STATS_PASSWORD:-admin}
    # 볼륨 설정
    volumes:
      # 설정 파일
      - ../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # SSL 인증서
      - /data/certs/combined:/etc/ssl/certs:ro
      - /data/certs/private:/etc/ssl/private:ro
      # 로그 및 데이터
      - /data/haproxy/logs:/var/log/haproxy:rw
      - /data/haproxy/lib:/var/lib/haproxy:rw
      - /data/haproxy/data:/usr/local/etc/haproxy/data:rw
      # 소켓 파일용 볼륨
      - /var/run/haproxy:/var/run/haproxy:rw
    # tmpfs 제거하고 권한 설정 변경
    restart: unless-stopped
    networks:
      - proxy-net
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8404 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # 보안 설정 추가
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    tmpfs:
      - /tmp:mode=1777
      - /run:mode=1777
    # 기본 명령어로 변경
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg

networks:
  proxy-net:
    driver: bridge
    # 네트워크 설정 추가
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    # 네트워크 격리 설정
    internal: false
